# -*- coding: utf-8 -*-
"""Plotly Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yTRzqMjMqp8IjkZeSYttPPg5B_BvfXoc

# Q1. Load the "titanic" dataset using the load_dataset function of seaborn. Use Plotly express to plot a scatter plot for age and fare columns in the titanic dataset.
"""

import plotly.graph_objects as pg

import seaborn as sns
Titanic = sns.load_dataset('titanic')

Titanic

fig = pg.Figure()
fig.add_trace(pg.Scatter(x = Titanic.age,y=Titanic.fare	, mode ='markers' ))

"""# Q2. Using the tips dataset in the Plotly library, plot a box plot using Plotly express."""

import plotly.express as px
import seaborn as sns
tips = sns.load_dataset('tips')
tips

fig = px.box(tips, x="day", y="total_bill")

fig

"""# Q3. Using the tips dataset in the Plotly library, Plot a histogram for x= "sex" and y="total_bill" column in the tips dataset. Also, use the "smoker" column with the pattern_shape parameter and the "day" column with the color parameter."""

px.histogram(tips, x="sex", y="total_bill", pattern_shape="smoker", color="day")

"""# Q4. Using the iris dataset in the Plotly library, Plot a scatter matrix plot, using the "species" column for the color parameter."""

iris = sns.load_dataset("iris")
iris

import plotly.express as px
px.scatter_matrix(iris,dimensions=["sepal_length", "sepal_width", "petal_length", "petal_width"],color="species")

"""# Q5. What is Distplot? Using Plotly express, plot a distplot.

The distplot (distribution plot) is a visualization tool commonly used to explore the distribution of a single variable in a dataset. It provides a combination of a histogram and a density estimation plot, allowing us to visualize the shape and spread of the data. Basically it use in Plotly tool.
"""

px.histogram(tips, x="total_bill", histnorm="probability density")